[project]
name = "morphological-change"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12.7"
dependencies = [
    "numpy>=2.1.3",
    "opencv-contrib-python>=4.10.0.84",
    "opencv-python>=4.10.0.84",
]
